# Site settings
title: Embedded.Systems | A blog about everything embedded and more
description: "A blog about embedded systems and more."
url: "http://www.google.com/"
author:
  name: "Embedded.Systems"
  email: "hello@jacoporabolini.com"
  url: "http://www.google.com"

# Build settings
baseurl: /home/sikenderashraf/Projects/kendiser5000-blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins: 
  - jekyll-paginate


# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
